export class Question{
    number;
    textContent;
    score;
}

export const questionTextInOrder = [
    "When I am working on something, I cannot relax until it is perfect",
    "I am not likely to criticize someone for giving up too easily",
    "It is not important that the people I am close to are successful",
    "I seldom criticize my friends for accepting second best",
    "I find it difficult to meet others' expectations of me",
    "One of my goals is to be perfect in everything I do",
    "Everything that others do must be of top-notch quality",
    "I never aim for perfection in my work",
    "Those around me readily accept that I can make mistakes too",
    "It doesn't matter when someone close to me does not do their absolute best",
    "The better I do, the better I am expected to do",
    "I seldom feel the need to be perfect",
    "Anything I do that is less than excellent will be seen as poor work by those around me",
    "I strive to be as perfect as I can be",
    "It is very important that I am perfect in everything I attempt",
    "I have high expectations for the people who are important to me",
    "I strive to be the best at everything I do",
    "The people around me expect me to succeed at everything I do",
    "I do not have very high expectations for those around me",
    "I demand nothing less than perfection from myself",
    "Others will like me even if I don't excel at everything",
    "I can't be bothered with people who won't strive to better themselves",
    "It makes me uneasy to see an error in my work",
    "I do not expect a lot from my friends",
    "Success means that I work even harder to please others",
    "If I ask someone to do something, I expect it to be done flawlessly",
    "I cannot stand to see people close to me make mistakes",
    "I am perfectionistic in setting my goals",
    "The people who matter to me should never let me down",
    "Others think I am okay, even when I do not succeed",
    "I feel that people are too demanding of me",
    "I must work to my full potential at all times",
    "Although they may not show it, other people get very upset with me when I slip up",
    "I do not have to be the best at whatever I am doing",
    "My family expects me to be perfect",
    "I do not have very high goals for myself",
    "My parents rarely expected me to excel in all aspects of my life",
    "I respect people who are average",
    "People expect nothing less than perfection from me",
    "I set very high standards for myself",
    "People expect more from me than I am capable of giving",
    "I must always be successful at school or work",
    "It does not matter to me when a close friend does not try their hardest",
    "People around me think I am still competent even if I make a mistake",
    "I seldom expect others to excel at whatever they do"
];